### ISSUE TITLE
Load QR Code Configuration Does not load image margin. Defaults to 0

### ISSUE THREAD

**Issue by manny-goti** [lyqht/mini-qr#29]
When loading a saved qr code configuration the following options are not loaded and defaults to 0
`"imageOptions":{"margin":5}}`

**Comment by lyqht** [comment]
Hello @manny-goti, could you provide more steps to replicate this? 

I tried a JSON with `"imageOptions":{"margin":20}}` and it works

[qr-code-config.json](https://github.com/lyqht/mini-qr/files/14155218/qr-code-config.1.json)
