### ISSUE TITLE
indentation trouble

### ISSUE THREAD

**Issue by cheluskin** [lyqht/mini-qr#38]
Some links destroy the default code indentation. For example, https://test.test/sdfsdfsdfsdfsdf
<img width="282" alt="Снимок экрана 2024-04-22 в 14 45 35" src="https://github.com/lyqht/mini-qr/assets/80083/702a49a8-6f74-4560-8112-ab205ec1f09d">

**Comment by lyqht** [comment]
what's the usual way of fixing this issue?

**Comment by lyqht** [comment]
or would adding padding be sufficient?

**Comment by lyqht** [comment]
With the new error correction levels feature from #46, this likely won't be a concern anymore.
