### ISSUE TITLE
SVG export has incorrect border radius

### ISSUE THREAD

**Issue by thorwebdev** [lyqht/mini-qr#59]
When exporting as SVG the border radius set to 0 is not applied correctly. Instead border radius of 48px is applied. PNG export is correctly done with no border.

Wonder if it's related to this line? https://github.com/lyqht/mini-qr/blob/main/src/utils/convertToImage.ts#L13

**Comment by lyqht** [comment]
Whoops, thank you for finding this bug! 😆

**Comment by lyqht** [comment]
Fixed the issue, here's an svg example with border radius 60px

![qr-code (1)](https://github.com/user-attachments/assets/dd22e8e1-b7e3-45b8-bf9e-38b9cee36d36)
